### ISSUE TITLE
Scheduler pausing

### ISSUE THREAD

**Issue by SkyQuant** [guryanovev/CrystalQuartz#32]
"Simple Scheduler" pausing if panel closed. To resume necessary to reload the site in browser and start again. How to make it working all the time.

**Comment by guryanovev** [comment]
The panel opening/closing should not affect scheduler in any way, so your issue is probably caused by some other reason, maybe related to scheduler lifecycle. Can you please share the code you use to create/initialise your scheduler instance?

**Comment by SkyQuant** [comment]
I just moved my Job to Owin based project and have the same problem setting up scheduler like in code here: https://github.com/guryanovev/CrystalQuartz/blob/master/examples/02_Owin_Web_Simple/CrystalQuartz.Samples.OwinSimple/Startup.cs

I have 3 executed task with 10 min interval and scheduler switches to pause. I don't know why.

**Comment by guryanovev** [comment]
Just double-checking, so the panel is working, but scheduler display as paused? yellow circle icon? What happens if you click "Start Scheduler" or other control buttons?

I can gues two variants:

1. If you are hosting the app inside IIS it might be AppPool shutting down issue (see https://technet.microsoft.com/en-us/library/cc771956(v=ws.10).aspx)

2. I never faced this problem but there is some evidence that GC can cause scheduler shutting down. (http://stackoverflow.com/questions/11082754/quart-net-suddenly-stops-triggering-jobs) This could be fixed by making `scheduler` static:

        public class Startup
        {
            public static IScheduler scheduler;

            public void Configuration(IAppBuilder app)
            {
                scheduler = StdSchedulerFactory.GetDefaultScheduler();
                //...
            }
        }

**Comment by SkyQuant** [comment]
Oh, I found that it depends on pricing plan chosen in Azure.  On Free option site goes "sleep" after half an hour and scheduler lights as yellow circle. But switching to Standard tariff makes it working without pauses. Sorry for alerting.
