### ISSUE TITLE
why my CrystalQuartzPanel doesn't draw the exec status?

### ISSUE THREAD

**Issue by DamonKiller** [guryanovev/CrystalQuartz#54]
the status of my jobs do not show in the right side.

Do I need to config something on somewhere?
[images](https://raw.githubusercontent.com/DamonKiller/Test4Jenkins/master/Snipaste_2018-08-30_16-21-42.png)
quartz on the servers.
crystalquartz on my computer (localhost)

thank you for any help.

**Comment by guryanovev** [comment]
Are you using remote scheduler? Sorry for confusion but timeline does not display for Remote Scheduler because the scheduler itself does not provide the required level of interactivity (no listeners, no info about running jobs etc). In fact Remote Scheduler uses obsolete .NET Remoting technology and it would be a good idea to avoid it if possible.

**Comment by DamonKiller** [comment]
thanks for reminding. 

I changed the way, and the timeline has work.

  <package id="CrystalQuartz.Owin" version="6.8.1" targetFramework="net47" />
  <package id="log4net" version="2.0.8" targetFramework="net47" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net47" />
  <package id="Microsoft.Owin.Host.HttpListener" version="4.0.0" targetFramework="net47" />
  <package id="Microsoft.Owin.Hosting" version="4.0.0" targetFramework="net47" />
  <package id="Owin" version="1.0" targetFramework="net47" />
  <package id="Quartz" version="3.0.6" targetFramework="net47" />
  <package id="Topshelf" version="4.0.4" targetFramework="net47" />

**Comment by djl394922860** [comment]
The same case with me , buy my quartz server is console application , o m g ! what should i do ?

**Comment by DamonKiller** [comment]
@djl394922860  same, on your quartz projects used like that. 

`//开启windowsService监测端 浏览器打开http://localhost:5555/quartz
Action<IAppBuilder> startup = app => { app.UseCrystalQuartz(() => scheduler); };
WebApp.Start("http://localhost:5555/", startup);`

**Comment by guryanovev** [comment]
@djl394922860, @DamonKiller 
There are some ways to work that around. First of all you might need to make your console app to use OWIN pipeline and act as a self-hosted web app. Next step would be installing `CrystalQuartz.Owin` to the console app and configure it to work with the scheduler. Since that, you would have a working Crystal Quartz panel hosted inside your app at a particular port (let's say it is port 9000). If you are OK with just looking at the panel locally (like http://localhost:9000/quartz) then you are done. But if the panel should be exposed to the internet, you migt need some more steps and there are options here.

1. You might just open the port (9000, for example) and expose your console app to the world directly (http://myserver:9000/quartz). 
2. It is possible to configure IIS to work as a reverse proxy to forward requests to console app like this: http://myserver/quartz -> localhost:9000/quartz
3. You probably already have a site (web app) so it is possible to use some sort of proxy middleware forwarding requests from some_site_url/quartz to localhost:9000/quartz.

These all are just basic ideas, things might depend on environment you have. Please also consider security issues if you go one of these ways.
